INSERT INTO students (name, email) VALUES
('icsp', 'icespice', 'iscp@colorado.edu', 'munch'),
('jandrich0', 'Janek', 'jandrich0@colorado.edu', 'default'),
('ghaslock1', 'Geri', 'ghaslock1@colorado.edu', 'default'),
('edeetlefs2', 'Ewen', 'edeetlefs2@colorado.edu', 'default'),
('tabbess3', 'Towney', 'tabbess3@colorado.edu', 'default'),
('gcolter4', 'Gradey', 'gcolter4@colorado.edu', 'default'),
('wspillman5', 'Willie', 'wspillman5@colorado.edu', 'default'),
('abaggally6', 'Aidan', 'abaggally6@colorado.edu', 'default'),
('blendrem7', 'Bee', 'blendrem7@colorado.edu', 'default'),
('ofumagalli8', 'Osborne', 'ofumagalli8@colorado.edu', 'default'),
('hslocket9', 'Hurleigh', 'hslocket9@colorado.edu', 'default'),
('frobartsa', 'Frederic', 'frobartsa@colorado.edu', 'default'),
('ffrereb', 'Fax', 'ffrereb@colorado.edu', 'default'),
('ldudlestonec', 'Leia', 'ldudlestonec@colorado.edu', 'default');

INSERT INTO tags (ski_or_board, first_name, mtn_name, skill_level) VALUES
('ski', 'Ice Spice', 'Copper', 2),
('ski', 'Janek', 'Eldora', 1),
('board', 'Geri', 'Copper', 2),
('board', 'Ewen', 'Winter Park', 3),
('board', 'Towney', 'Copper', 3),
('ski', 'Gradey', 'Breckenridge', 4),
('board', 'Willie', 'Eldora', 1),
('board', 'Aidan', 'Eldora', 2),
('ski', 'Bee', 'Winter Park', 1),
('ski', 'Osborne', 'Breckenridge', 1),
('ski', 'Hurleigh', 'Copper', 1),
('ski', 'Frederic', 'Eldora', 2),
('board', 'Fax', 'Winter Park', 3),
('board', 'Leia', 'Breckenridge', 4);