INSERT INTO students (username, name, email, password) VALUES
('icsp', 'Ice Spice', 'iscp@colorado.edu', 'munch'),
('jandrich0', 'Janek', 'jandrich0@colorado.edu', 'default'),
('ghaslock1', 'Geri', 'ghaslock1@colorado.edu', 'default'),
('edeetlefs2', 'Ewen', 'edeetlefs2@colorado.edu', 'default'),
('tabbess3', 'Towney', 'tabbess3@colorado.edu', 'default'),
('gcolter4', 'Gradey', 'gcolter4@colorado.edu', 'default'),
('wspillman5', 'Willie', 'wspillman5@colorado.edu', 'default'),
('abaggally6', 'Aidan', 'abaggally6@colorado.edu', 'default'),
('blendrem7', 'Bee', 'blendrem7@colorado.edu', 'default'),
('ofumagalli8', 'Osborne', 'ofumagalli8@colorado.edu', 'default'),
('hslocket9', 'Hurleigh', 'hslocket9@colorado.edu', 'default'),
('frobartsa', 'Frederic', 'frobartsa@colorado.edu', 'default'),
('ffrereb', 'Fax', 'ffrereb@colorado.edu', 'default'),
('ldudlestonec', 'Leia', 'ldudlestonec@colorado.edu', 'default');

INSERT INTO tags (ski_or_board, username, mtn_name, skill_level) VALUES
('ski', 'icsp', 'Copper', 2),
('ski', 'jandrich0', 'Eldora', 1),
('board', 'ghaslock1', 'Copper', 2),
('board', 'edeetlefs2', 'Winter Park', 3),
('board', 'tabbess3', 'Copper', 3),
('ski', 'gcolter4', 'Breckenridge', 4),
('board', 'wspillman5', 'Eldora', 1),
('board', 'abaggally6', 'Eldora', 2),
('ski', 'blendrem7', 'Winter Park', 1),
('ski', 'ofumagalli8', 'Breckenridge', 1),
('ski', 'hslocket9', 'Copper', 1),
('ski', 'frobartsa', 'Eldora', 2),
('board', 'ffrereb', 'Winter Park', 3),
('board', 'ldudlestonec', 'Breckenridge', 4);